# Generated by Django 5.2.5 on 2026-01-05 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=150)),
                ('division', models.CharField(max_length=150)),
                ('oic_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DSDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_divisions', to='members.district')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etf_no', models.CharField(max_length=50, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('nic_no', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('workplace', models.CharField(max_length=255)),
                ('salary_bank_branch_no', models.CharField(max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('provincial_council', models.CharField(blank=True, max_length=150, null=True)),
                ('acc_no', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('date_resigned', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_children', models.IntegerField(default=0)),
                ('education_qualifications', models.TextField()),
                ('experience', models.TextField()),
                ('position_category', models.CharField(max_length=100)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.district')),
                ('ds_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.dsdivision')),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.policestation')),
            ],
        ),
    ]
