# Generated by Django 5.2.5 on 2026-01-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
