# Generated by Django 5.1.4 on 2026-01-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(default=0)),
                ('member_etf_no', models.CharField(default='', max_length=50)),
                ('member_fullname', models.CharField(default='', max_length=255)),
                ('attendance_month', models.DateField()),
                ('service_days', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'ordering': ['-attendance_month', 'member_etf_no'],
                'unique_together': {('member_id', 'attendance_month')},
            },
        ),
    ]
