# Generated by Django 5.1.4 on 2026-01-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_add_member_fields_to_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position_category',
            field=models.CharField(choices=[('Security', 'Security'), ('Cleaning', 'Cleaning')], max_length=100),
        ),
    ]
