# Generated by Django 6.0.2 on 2026-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_position_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='veteran_status',
            field=models.CharField(choices=[('Veteran', 'Veteran'), ('Non-Veteran', 'Non-Veteran')], default='Non-Veteran', max_length=20),
        ),
    ]
