# Generated by Django 6.0.2 on 2026-02-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_veteran_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_place', models.CharField(max_length=255)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_history', to='members.member')),
            ],
        ),
    ]
