# Generated by Django 6.0.2 on 2026-02-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_assignedhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leave_dates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
